require 'test/unit'
require 'libzfs'

class ZsfErrorTest < Test::Unit::TestCase
  def test_zfs_errors_defined
    assert defined?(ZfsError)
    assert defined?(ZfsError::Error)
    assert_equal StandardError, ZfsError::Error.superclass
    assert defined?(ZfsError::NoMemoryError)
    assert_equal ZfsError::Error, ZfsError::NoMemoryError.superclass

    assert defined?(ZfsError::InvalidPropertyError)
    assert defined?(ZfsError::ReadOnlyPropertyError)
    assert defined?(ZfsError::InvalidPropertyTypeError)
    assert defined?(ZfsError::NonInheritablePropertyError)
    assert defined?(ZfsError::PropertySpaceError)
    assert defined?(ZfsError::InvalidDatasetTypeError)
    assert defined?(ZfsError::DatasetBusyError)
    assert defined?(ZfsError::DatasetExistsError)
    assert defined?(ZfsError::NoentError)
    assert defined?(ZfsError::BadStreamError)
    assert defined?(ZfsError::DatasetReadOnlyError)
    assert defined?(ZfsError::VolumeTooBigError)
    assert defined?(ZfsError::InvalidNameError)
    assert defined?(ZfsError::BadRestoreError)
    assert defined?(ZfsError::BadBackupError)
    assert defined?(ZfsError::BadTargetError)
    assert defined?(ZfsError::NoDeviceError)
    assert defined?(ZfsError::BadDeviceError)
    assert defined?(ZfsError::NoReplicasError)
    assert defined?(ZfsError::ResilveringError)
    assert defined?(ZfsError::BadVersionError)
    assert defined?(ZfsError::PoolUnavailableError)
    assert defined?(ZfsError::DeviceOverflowError)
    assert defined?(ZfsError::BadPathError)
    assert defined?(ZfsError::CrossTargetError)
    assert defined?(ZfsError::ZonedError)
    assert defined?(ZfsError::MountFailedError)
    assert defined?(ZfsError::UnmountFailedError)
    assert defined?(ZfsError::UnshareNfsFailedError)
    assert defined?(ZfsError::ShareNfsFailedError)
    assert defined?(ZfsError::UnshareSmbFailedError);
    assert defined?(ZfsError::ShareSmbFailedError)
    assert defined?(ZfsError::PermError)
    assert defined?(ZfsError::NospcError)
    assert defined?(ZfsError::FaultError)
    assert defined?(ZfsError::IOError)
    assert defined?(ZfsError::INTRError)
    assert defined?(ZfsError::IsSpareError)
    assert defined?(ZfsError::InvalidConfigError)
    assert defined?(ZfsError::RecursiveError)
    assert defined?(ZfsError::NoHistoryError)
    assert defined?(ZfsError::PoolPropsError)
    assert defined?(ZfsError::PoolNotSupportedError)
    assert defined?(ZfsError::PoolInvalidArgError)
    assert defined?(ZfsError::NameTooLongError)
    assert defined?(ZfsError::OpenFailedError)
    assert defined?(ZfsError::NoCapError)
    assert defined?(ZfsError::LabelFailedError)
    assert defined?(ZfsError::BadWhoError)
    assert defined?(ZfsError::BadPermError)
    assert defined?(ZfsError::BadPermSetError)
    assert defined?(ZfsError::NoDelegationError)
    assert defined?(ZfsError::PermReadOnlyError)
    assert defined?(ZfsError::BadCacheError)
    assert defined?(ZfsError::IsL2CacheError)
    assert defined?(ZfsError::VdevNotSupportedError)
    assert defined?(ZfsError::NotSupportedError)
    assert defined?(ZfsError::ActiveSpareError)
    assert defined?(ZfsError::UnplayedLogsError)
    assert defined?(ZfsError::ReftagReleError)
    assert defined?(ZfsError::ReftagHoldError)
    assert defined?(ZfsError::TagTooLongError)
    assert defined?(ZfsError::PipeFailedError)
    assert defined?(ZfsError::ThreadCreateFailedError)
    assert defined?(ZfsError::PostSplitOnlineError)

  end
end
